server:
  port: 8080

feign:
  client:
    config:
      default:
        loggerLevel: full

jobs:
  cronSchedule:

monitoring:
  sonarqube:
    api.url:
    component.keys:
  slack:
    token:
    channel:
      id:
      name:
    admin.id: # ex) "@jj"

logging:
  level:
    com.lzdk.monitoring: debug